name: Deploy API via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Upload project to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r . ec2-user@${{ secrets.HOST }}:/home/ec2-user/ecommerce-api

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST }} << 'EOF'
            cd /home/ec2-user/ecommerce-api
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
